# Overseerr services.yaml entries
submit_movie_request:
  description: Searches for a movie and requests the first result, or requests by ID.
  fields:
    name:
      description: Search parameter (optional if media_id is provided)
      example: "beverly hills cop"
    media_id:
      description: TMDB ID of the movie (optional)
      example: 90

submit_tv_request:
  description: Searches for a TV show and requests the first result, or requests by ID.
  fields:
    name:
      description: Search parameter (optional if media_id is provided)
      example: "breaking bad"
    media_id:
      description: TMDB ID of the TV/Show (optional)
      example: 1396
    season:
      description: Which season(s) to request (first, latest or all)
      example: "latest"

submit_music_request:
  description: Searches for a music album and requests the first result, or requests by ID.
  fields:
    name:
      description: Search parameter (optional if media_id is provided)
      example: "nevermind"
    media_id:
      description: Music Album ID (optional)
      example: "12345"

update_request:
  description: Updates the status of specified request to pending/approve/decline/available
  fields:
    request_id:
      description: ID of the request to update
      example: 30
    new_status:
      description: New Status (can be pending/approve/decline/available)
      example: "approve"

search_movies:
  description: Searches for movies and returns a list of results.
  fields:
    name:
      description: Search parameter
      example: "matrix"

search_tv:
  description: Searches for TV shows and returns a list of results.
  fields:
    name:
      description: Search parameter
      example: "breaking bad"

search_music:
  description: Searches for music albums and returns a list of results.
  fields:
    name:
      description: Search parameter
      example: "nevermind"
